name: "install uv"
description: "Installs uv using the community action"
runs:
  using: composite
  steps:
    - name: install uv
      uses: astral-sh/setup-uv@v8
      with:
          version: "0.11.15"