name: "install uv"
description: "Installs uv using the community action"
runs:
  using: composite
  steps:
    - name: install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        version: "0.11.15"